<?php

// This file was generated by running "composer dump-env prod"

return array (
  'APP_ENV' => 'prod',
  'APP_SECRET' => 'baca38b8bfe77a56f3cdc24251df32fb',
  'DATABASE_URL' => 'mysql://wmcodeovyrroot:Azertyuiop123@127.0.0.1:3306/wmcodeovyrroot',
  'MAILER_URL' => 'null://localhost',
);
