<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.TW0SQ.q' shared service.

return $this->privates['.service_locator.TW0SQ.q'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'classementRepo' => ['privates', 'App\\Repository\\ClassementRepository', 'getClassementRepositoryService.php', true],
    'manager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService.php', true],
    'match' => ['privates', '.errored..service_locator.TW0SQ.q.App\\Entity\\Matchs', NULL, 'Cannot autowire service ".service_locator.TW0SQ.q": it references class "App\\Entity\\Matchs" but no such service exists.'],
    'matchRepo' => ['privates', 'App\\Repository\\MatchsRepository', 'getMatchsRepositoryService.php', true],
], [
    'classementRepo' => 'App\\Repository\\ClassementRepository',
    'manager' => '?',
    'match' => 'App\\Entity\\Matchs',
    'matchRepo' => 'App\\Repository\\MatchsRepository',
]);
