<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPY5xEPK\srcApp_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPY5xEPK/srcApp_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerPY5xEPK.legacy');

    return;
}

if (!\class_exists(srcApp_KernelProdContainer::class, false)) {
    \class_alias(\ContainerPY5xEPK\srcApp_KernelProdContainer::class, srcApp_KernelProdContainer::class, false);
}

return new \ContainerPY5xEPK\srcApp_KernelProdContainer([
    'container.build_hash' => 'PY5xEPK',
    'container.build_id' => '9bfbe63d',
    'container.build_time' => 1572516510,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPY5xEPK');
