<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.7HBZaTu' shared service.

return $this->privates['.service_locator.7HBZaTu'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'cache' => ['services', 'liip_imagine.cache.manager', 'getLiipImagine_Cache_ManagerService', false],
    'helper' => ['services', 'vich_uploader.templating.helper.uploader_helper', 'getVichUploader_Templating_Helper_UploaderHelperService', false],
    'manager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
], [
    'cache' => '?',
    'helper' => '?',
    'manager' => '?',
]);
