<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.Ms.2c_u' shared service.

return $this->privates['.service_locator.Ms.2c_u'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'classementRepo' => ['privates', 'App\\Repository\\ClassementRepository', 'getClassementRepositoryService.php', true],
    'repo' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService.php', true],
    'user' => ['privates', '.errored..service_locator.Ms.2c_u.Symfony\\Component\\Security\\Core\\User\\UserInterface', NULL, 'Cannot autowire service ".service_locator.Ms.2c_u": it references interface "Symfony\\Component\\Security\\Core\\User\\UserInterface" but no such service exists. Did you create a class that implements this interface?'],
], [
    'classementRepo' => 'App\\Repository\\ClassementRepository',
    'repo' => 'App\\Repository\\UserRepository',
    'user' => 'Symfony\\Component\\Security\\Core\\User\\UserInterface',
]);
