<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.f7WnzOZ' shared service.

return $this->privates['.service_locator.f7WnzOZ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\AdminController::ChampionnatClose' => ['privates', '.service_locator.0om4HxW', 'get_ServiceLocator_0om4HxWService.php', true],
    'App\\Controller\\AdminController::ChampionnatShow' => ['privates', '.service_locator.5c8P3v8', 'get_ServiceLocator_5c8P3v8Service.php', true],
    'App\\Controller\\AdminController::delete' => ['privates', '.service_locator.TW0SQ.q', 'get_ServiceLocator_TW0SQ_QService.php', true],
    'App\\Controller\\AdminController::edit' => ['privates', '.service_locator.60Q35to', 'get_ServiceLocator_60Q35toService.php', true],
    'App\\Controller\\AdminController::editMatch' => ['privates', '.service_locator.kaxlnas', 'get_ServiceLocator_KaxlnasService.php', true],
    'App\\Controller\\AdminController::index' => ['privates', '.service_locator.Ms.2c_u', 'get_ServiceLocator_Ms_2cUService.php', true],
    'App\\Controller\\AdminController::inscription' => ['privates', '.service_locator.7HBZaTu', 'get_ServiceLocator_7HBZaTuService.php', true],
    'App\\Controller\\AdminController::update' => ['privates', '.service_locator.7HBZaTu', 'get_ServiceLocator_7HBZaTuService.php', true],
    'App\\Controller\\ProfileController::index' => ['privates', '.service_locator.kRTjdlh', 'get_ServiceLocator_KRTjdlhService.php', true],
    'App\\Controller\\SecurityController::index' => ['privates', '.service_locator.EbLunuf', 'get_ServiceLocator_EbLunufService.php', true],
    'App\\Controller\\TournamentController::index' => ['privates', '.service_locator.CsbCtJa', 'get_ServiceLocator_CsbCtJaService.php', true],
    'App\\Controller\\AdminController:ChampionnatClose' => ['privates', '.service_locator.0om4HxW', 'get_ServiceLocator_0om4HxWService.php', true],
    'App\\Controller\\AdminController:ChampionnatShow' => ['privates', '.service_locator.5c8P3v8', 'get_ServiceLocator_5c8P3v8Service.php', true],
    'App\\Controller\\AdminController:delete' => ['privates', '.service_locator.TW0SQ.q', 'get_ServiceLocator_TW0SQ_QService.php', true],
    'App\\Controller\\AdminController:edit' => ['privates', '.service_locator.60Q35to', 'get_ServiceLocator_60Q35toService.php', true],
    'App\\Controller\\AdminController:editMatch' => ['privates', '.service_locator.kaxlnas', 'get_ServiceLocator_KaxlnasService.php', true],
    'App\\Controller\\AdminController:index' => ['privates', '.service_locator.Ms.2c_u', 'get_ServiceLocator_Ms_2cUService.php', true],
    'App\\Controller\\AdminController:inscription' => ['privates', '.service_locator.7HBZaTu', 'get_ServiceLocator_7HBZaTuService.php', true],
    'App\\Controller\\AdminController:update' => ['privates', '.service_locator.7HBZaTu', 'get_ServiceLocator_7HBZaTuService.php', true],
    'App\\Controller\\ProfileController:index' => ['privates', '.service_locator.kRTjdlh', 'get_ServiceLocator_KRTjdlhService.php', true],
    'App\\Controller\\SecurityController:index' => ['privates', '.service_locator.EbLunuf', 'get_ServiceLocator_EbLunufService.php', true],
    'App\\Controller\\TournamentController:index' => ['privates', '.service_locator.CsbCtJa', 'get_ServiceLocator_CsbCtJaService.php', true],
], [
    'App\\Controller\\AdminController::ChampionnatClose' => '?',
    'App\\Controller\\AdminController::ChampionnatShow' => '?',
    'App\\Controller\\AdminController::delete' => '?',
    'App\\Controller\\AdminController::edit' => '?',
    'App\\Controller\\AdminController::editMatch' => '?',
    'App\\Controller\\AdminController::index' => '?',
    'App\\Controller\\AdminController::inscription' => '?',
    'App\\Controller\\AdminController::update' => '?',
    'App\\Controller\\ProfileController::index' => '?',
    'App\\Controller\\SecurityController::index' => '?',
    'App\\Controller\\TournamentController::index' => '?',
    'App\\Controller\\AdminController:ChampionnatClose' => '?',
    'App\\Controller\\AdminController:ChampionnatShow' => '?',
    'App\\Controller\\AdminController:delete' => '?',
    'App\\Controller\\AdminController:edit' => '?',
    'App\\Controller\\AdminController:editMatch' => '?',
    'App\\Controller\\AdminController:index' => '?',
    'App\\Controller\\AdminController:inscription' => '?',
    'App\\Controller\\AdminController:update' => '?',
    'App\\Controller\\ProfileController:index' => '?',
    'App\\Controller\\SecurityController:index' => '?',
    'App\\Controller\\TournamentController:index' => '?',
]);
