<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQ7XHKdM\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQ7XHKdM/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQ7XHKdM.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQ7XHKdM\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerQ7XHKdM\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'Q7XHKdM',
    'container.build_id' => '451c0308',
    'container.build_time' => 1572450924,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQ7XHKdM');
