<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Matchs extends \App\Entity\Matchs implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Matchs' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Matchs' . "\0" . 'Joueurs1', '' . "\0" . 'App\\Entity\\Matchs' . "\0" . 'resultat_j1', '' . "\0" . 'App\\Entity\\Matchs' . "\0" . 'Joueurs2', '' . "\0" . 'App\\Entity\\Matchs' . "\0" . 'resultat_j2', '' . "\0" . 'App\\Entity\\Matchs' . "\0" . 'championnat', '' . "\0" . 'App\\Entity\\Matchs' . "\0" . 'journee'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Matchs' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Matchs' . "\0" . 'Joueurs1', '' . "\0" . 'App\\Entity\\Matchs' . "\0" . 'resultat_j1', '' . "\0" . 'App\\Entity\\Matchs' . "\0" . 'Joueurs2', '' . "\0" . 'App\\Entity\\Matchs' . "\0" . 'resultat_j2', '' . "\0" . 'App\\Entity\\Matchs' . "\0" . 'championnat', '' . "\0" . 'App\\Entity\\Matchs' . "\0" . 'journee'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Matchs $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getJoueurs1(): ?\App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getJoueurs1', []);

        return parent::getJoueurs1();
    }

    /**
     * {@inheritDoc}
     */
    public function setJoueurs1(?\App\Entity\User $Joueurs1): \App\Entity\Matchs
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setJoueurs1', [$Joueurs1]);

        return parent::setJoueurs1($Joueurs1);
    }

    /**
     * {@inheritDoc}
     */
    public function getResultatJ1(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getResultatJ1', []);

        return parent::getResultatJ1();
    }

    /**
     * {@inheritDoc}
     */
    public function setResultatJ1(?int $resultat_j1): \App\Entity\Matchs
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setResultatJ1', [$resultat_j1]);

        return parent::setResultatJ1($resultat_j1);
    }

    /**
     * {@inheritDoc}
     */
    public function getJoueurs2(): ?\App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getJoueurs2', []);

        return parent::getJoueurs2();
    }

    /**
     * {@inheritDoc}
     */
    public function setJoueurs2(?\App\Entity\User $Joueurs2): \App\Entity\Matchs
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setJoueurs2', [$Joueurs2]);

        return parent::setJoueurs2($Joueurs2);
    }

    /**
     * {@inheritDoc}
     */
    public function getResultatJ2(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getResultatJ2', []);

        return parent::getResultatJ2();
    }

    /**
     * {@inheritDoc}
     */
    public function setResultatJ2(?int $resultat_j2): \App\Entity\Matchs
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setResultatJ2', [$resultat_j2]);

        return parent::setResultatJ2($resultat_j2);
    }

    /**
     * {@inheritDoc}
     */
    public function getChampionnat(): ?\App\Entity\Championnats
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getChampionnat', []);

        return parent::getChampionnat();
    }

    /**
     * {@inheritDoc}
     */
    public function setChampionnat(?\App\Entity\Championnats $championnat): \App\Entity\Matchs
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setChampionnat', [$championnat]);

        return parent::setChampionnat($championnat);
    }

    /**
     * {@inheritDoc}
     */
    public function getJournee(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getJournee', []);

        return parent::getJournee();
    }

    /**
     * {@inheritDoc}
     */
    public function setJournee(?int $journee): \App\Entity\Matchs
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setJournee', [$journee]);

        return parent::setJournee($journee);
    }

}
